version: "3"
#TO_DO: Port node
services:
  node:
    # build: .
    image: node:16
    working_dir: /app
    volumes:
      - ./:/app
    container_name: delivery_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3003:3003
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
  db:
    container_name: delivery_api_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: api_net